site-url: https://www.marceloomens.com
publish-mode: editorial_workflow
backend:
  name: github
  repo: marceloomens/twenty19
  branch: master
collections:
- name: "posts"
  label: "Cards"
  label_singular: "Card"
  folder: "content/posts"
  create: true
  slug: "{{slug}}"
  fields:
  - {label: "Title", name: "title", widget: "string"}
  - {label: "Icon (entypo.com)", name: "icon", widget: "string"}
  - {label: "Image", name: "image", widget: "image"}
  - {label: "Date", name: "date", widget: "hidden"}
  - {label: "Draft", name: "draft", widget: "hidden", default: false}
  - {label: "Sticky", name: "sticky", widget: "boolean", default: false}
  - {label: "Content", name: "body", widget: "markdown"}
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
