backend:
  name: github
  repo: marceloomens/twenty19
  branch: master
collections:
- name: "posts"
  label: "Updates"
  folder: "content/posts"
  create: true
  slug: "{{slug}}"
  fields:
  - {label: "Title", name: "title", widget: "string"}
  - {label: "Content", name: "body", widget: "markdown"}
  - {label: "Sticky", name: "sticky", widget: "boolean", default: false}
  - {label: "Icon", name: "icon", widget: "string"}
  - {label: "Featured image", name: "image", widget: "image"}
publish-mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
